/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package guide.atech.schema.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PosInvoice extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4477307303694713601L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PosInvoice\",\"namespace\":\"guide.atech.schema.avro\",\"fields\":[{\"name\":\"InvoiceNumber\",\"type\":[\"null\",\"string\"]},{\"name\":\"CreatedTime\",\"type\":[\"null\",\"long\"]},{\"name\":\"TotalAmount\",\"type\":[\"null\",\"double\"]},{\"name\":\"NumberOfItems\",\"type\":[\"null\",\"int\"]},{\"name\":\"DeliveryAddress\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DeliveryAddress\",\"fields\":[{\"name\":\"AddressLine\",\"type\":[\"null\",\"string\"]},{\"name\":\"City\",\"type\":[\"null\",\"string\"]},{\"name\":\"State\",\"type\":[\"null\",\"string\"]},{\"name\":\"ContactNumber\",\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"InvoiceLineItems\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"LineItem\",\"fields\":[{\"name\":\"ItemCode\",\"type\":[\"null\",\"string\"]},{\"name\":\"ItemDescription\",\"type\":[\"null\",\"string\"]},{\"name\":\"ItemPrice\",\"type\":[\"null\",\"double\"]},{\"name\":\"ItemQty\",\"type\":[\"null\",\"int\"]},{\"name\":\"TotalValue\",\"type\":[\"null\",\"double\"]}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence InvoiceNumber;
  @Deprecated public java.lang.Long CreatedTime;
  @Deprecated public java.lang.Double TotalAmount;
  @Deprecated public java.lang.Integer NumberOfItems;
  @Deprecated public guide.atech.schema.avro.DeliveryAddress DeliveryAddress;
  @Deprecated public java.util.List<guide.atech.schema.avro.LineItem> InvoiceLineItems;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PosInvoice() {}

  /**
   * All-args constructor.
   * @param InvoiceNumber The new value for InvoiceNumber
   * @param CreatedTime The new value for CreatedTime
   * @param TotalAmount The new value for TotalAmount
   * @param NumberOfItems The new value for NumberOfItems
   * @param DeliveryAddress The new value for DeliveryAddress
   * @param InvoiceLineItems The new value for InvoiceLineItems
   */
  public PosInvoice(java.lang.CharSequence InvoiceNumber, java.lang.Long CreatedTime, java.lang.Double TotalAmount, java.lang.Integer NumberOfItems, guide.atech.schema.avro.DeliveryAddress DeliveryAddress, java.util.List<guide.atech.schema.avro.LineItem> InvoiceLineItems) {
    this.InvoiceNumber = InvoiceNumber;
    this.CreatedTime = CreatedTime;
    this.TotalAmount = TotalAmount;
    this.NumberOfItems = NumberOfItems;
    this.DeliveryAddress = DeliveryAddress;
    this.InvoiceLineItems = InvoiceLineItems;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return InvoiceNumber;
    case 1: return CreatedTime;
    case 2: return TotalAmount;
    case 3: return NumberOfItems;
    case 4: return DeliveryAddress;
    case 5: return InvoiceLineItems;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: InvoiceNumber = (java.lang.CharSequence)value$; break;
    case 1: CreatedTime = (java.lang.Long)value$; break;
    case 2: TotalAmount = (java.lang.Double)value$; break;
    case 3: NumberOfItems = (java.lang.Integer)value$; break;
    case 4: DeliveryAddress = (guide.atech.schema.avro.DeliveryAddress)value$; break;
    case 5: InvoiceLineItems = (java.util.List<guide.atech.schema.avro.LineItem>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'InvoiceNumber' field.
   * @return The value of the 'InvoiceNumber' field.
   */
  public java.lang.CharSequence getInvoiceNumber() {
    return InvoiceNumber;
  }

  /**
   * Sets the value of the 'InvoiceNumber' field.
   * @param value the value to set.
   */
  public void setInvoiceNumber(java.lang.CharSequence value) {
    this.InvoiceNumber = value;
  }

  /**
   * Gets the value of the 'CreatedTime' field.
   * @return The value of the 'CreatedTime' field.
   */
  public java.lang.Long getCreatedTime() {
    return CreatedTime;
  }

  /**
   * Sets the value of the 'CreatedTime' field.
   * @param value the value to set.
   */
  public void setCreatedTime(java.lang.Long value) {
    this.CreatedTime = value;
  }

  /**
   * Gets the value of the 'TotalAmount' field.
   * @return The value of the 'TotalAmount' field.
   */
  public java.lang.Double getTotalAmount() {
    return TotalAmount;
  }

  /**
   * Sets the value of the 'TotalAmount' field.
   * @param value the value to set.
   */
  public void setTotalAmount(java.lang.Double value) {
    this.TotalAmount = value;
  }

  /**
   * Gets the value of the 'NumberOfItems' field.
   * @return The value of the 'NumberOfItems' field.
   */
  public java.lang.Integer getNumberOfItems() {
    return NumberOfItems;
  }

  /**
   * Sets the value of the 'NumberOfItems' field.
   * @param value the value to set.
   */
  public void setNumberOfItems(java.lang.Integer value) {
    this.NumberOfItems = value;
  }

  /**
   * Gets the value of the 'DeliveryAddress' field.
   * @return The value of the 'DeliveryAddress' field.
   */
  public guide.atech.schema.avro.DeliveryAddress getDeliveryAddress() {
    return DeliveryAddress;
  }

  /**
   * Sets the value of the 'DeliveryAddress' field.
   * @param value the value to set.
   */
  public void setDeliveryAddress(guide.atech.schema.avro.DeliveryAddress value) {
    this.DeliveryAddress = value;
  }

  /**
   * Gets the value of the 'InvoiceLineItems' field.
   * @return The value of the 'InvoiceLineItems' field.
   */
  public java.util.List<guide.atech.schema.avro.LineItem> getInvoiceLineItems() {
    return InvoiceLineItems;
  }

  /**
   * Sets the value of the 'InvoiceLineItems' field.
   * @param value the value to set.
   */
  public void setInvoiceLineItems(java.util.List<guide.atech.schema.avro.LineItem> value) {
    this.InvoiceLineItems = value;
  }

  /**
   * Creates a new PosInvoice RecordBuilder.
   * @return A new PosInvoice RecordBuilder
   */
  public static guide.atech.schema.avro.PosInvoice.Builder newBuilder() {
    return new guide.atech.schema.avro.PosInvoice.Builder();
  }

  /**
   * Creates a new PosInvoice RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PosInvoice RecordBuilder
   */
  public static guide.atech.schema.avro.PosInvoice.Builder newBuilder(guide.atech.schema.avro.PosInvoice.Builder other) {
    return new guide.atech.schema.avro.PosInvoice.Builder(other);
  }

  /**
   * Creates a new PosInvoice RecordBuilder by copying an existing PosInvoice instance.
   * @param other The existing instance to copy.
   * @return A new PosInvoice RecordBuilder
   */
  public static guide.atech.schema.avro.PosInvoice.Builder newBuilder(guide.atech.schema.avro.PosInvoice other) {
    return new guide.atech.schema.avro.PosInvoice.Builder(other);
  }

  /**
   * RecordBuilder for PosInvoice instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PosInvoice>
    implements org.apache.avro.data.RecordBuilder<PosInvoice> {

    private java.lang.CharSequence InvoiceNumber;
    private java.lang.Long CreatedTime;
    private java.lang.Double TotalAmount;
    private java.lang.Integer NumberOfItems;
    private guide.atech.schema.avro.DeliveryAddress DeliveryAddress;
    private guide.atech.schema.avro.DeliveryAddress.Builder DeliveryAddressBuilder;
    private java.util.List<guide.atech.schema.avro.LineItem> InvoiceLineItems;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(guide.atech.schema.avro.PosInvoice.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.InvoiceNumber)) {
        this.InvoiceNumber = data().deepCopy(fields()[0].schema(), other.InvoiceNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CreatedTime)) {
        this.CreatedTime = data().deepCopy(fields()[1].schema(), other.CreatedTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.TotalAmount)) {
        this.TotalAmount = data().deepCopy(fields()[2].schema(), other.TotalAmount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.NumberOfItems)) {
        this.NumberOfItems = data().deepCopy(fields()[3].schema(), other.NumberOfItems);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.DeliveryAddress)) {
        this.DeliveryAddress = data().deepCopy(fields()[4].schema(), other.DeliveryAddress);
        fieldSetFlags()[4] = true;
      }
      if (other.hasDeliveryAddressBuilder()) {
        this.DeliveryAddressBuilder = guide.atech.schema.avro.DeliveryAddress.newBuilder(other.getDeliveryAddressBuilder());
      }
      if (isValidValue(fields()[5], other.InvoiceLineItems)) {
        this.InvoiceLineItems = data().deepCopy(fields()[5].schema(), other.InvoiceLineItems);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PosInvoice instance
     * @param other The existing instance to copy.
     */
    private Builder(guide.atech.schema.avro.PosInvoice other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.InvoiceNumber)) {
        this.InvoiceNumber = data().deepCopy(fields()[0].schema(), other.InvoiceNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CreatedTime)) {
        this.CreatedTime = data().deepCopy(fields()[1].schema(), other.CreatedTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.TotalAmount)) {
        this.TotalAmount = data().deepCopy(fields()[2].schema(), other.TotalAmount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.NumberOfItems)) {
        this.NumberOfItems = data().deepCopy(fields()[3].schema(), other.NumberOfItems);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.DeliveryAddress)) {
        this.DeliveryAddress = data().deepCopy(fields()[4].schema(), other.DeliveryAddress);
        fieldSetFlags()[4] = true;
      }
      this.DeliveryAddressBuilder = null;
      if (isValidValue(fields()[5], other.InvoiceLineItems)) {
        this.InvoiceLineItems = data().deepCopy(fields()[5].schema(), other.InvoiceLineItems);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'InvoiceNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getInvoiceNumber() {
      return InvoiceNumber;
    }

    /**
      * Sets the value of the 'InvoiceNumber' field.
      * @param value The value of 'InvoiceNumber'.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder setInvoiceNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.InvoiceNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'InvoiceNumber' field has been set.
      * @return True if the 'InvoiceNumber' field has been set, false otherwise.
      */
    public boolean hasInvoiceNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'InvoiceNumber' field.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder clearInvoiceNumber() {
      InvoiceNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'CreatedTime' field.
      * @return The value.
      */
    public java.lang.Long getCreatedTime() {
      return CreatedTime;
    }

    /**
      * Sets the value of the 'CreatedTime' field.
      * @param value The value of 'CreatedTime'.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder setCreatedTime(java.lang.Long value) {
      validate(fields()[1], value);
      this.CreatedTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'CreatedTime' field has been set.
      * @return True if the 'CreatedTime' field has been set, false otherwise.
      */
    public boolean hasCreatedTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'CreatedTime' field.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder clearCreatedTime() {
      CreatedTime = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'TotalAmount' field.
      * @return The value.
      */
    public java.lang.Double getTotalAmount() {
      return TotalAmount;
    }

    /**
      * Sets the value of the 'TotalAmount' field.
      * @param value The value of 'TotalAmount'.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder setTotalAmount(java.lang.Double value) {
      validate(fields()[2], value);
      this.TotalAmount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'TotalAmount' field has been set.
      * @return True if the 'TotalAmount' field has been set, false otherwise.
      */
    public boolean hasTotalAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'TotalAmount' field.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder clearTotalAmount() {
      TotalAmount = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'NumberOfItems' field.
      * @return The value.
      */
    public java.lang.Integer getNumberOfItems() {
      return NumberOfItems;
    }

    /**
      * Sets the value of the 'NumberOfItems' field.
      * @param value The value of 'NumberOfItems'.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder setNumberOfItems(java.lang.Integer value) {
      validate(fields()[3], value);
      this.NumberOfItems = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'NumberOfItems' field has been set.
      * @return True if the 'NumberOfItems' field has been set, false otherwise.
      */
    public boolean hasNumberOfItems() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'NumberOfItems' field.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder clearNumberOfItems() {
      NumberOfItems = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'DeliveryAddress' field.
      * @return The value.
      */
    public guide.atech.schema.avro.DeliveryAddress getDeliveryAddress() {
      return DeliveryAddress;
    }

    /**
      * Sets the value of the 'DeliveryAddress' field.
      * @param value The value of 'DeliveryAddress'.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder setDeliveryAddress(guide.atech.schema.avro.DeliveryAddress value) {
      validate(fields()[4], value);
      this.DeliveryAddressBuilder = null;
      this.DeliveryAddress = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'DeliveryAddress' field has been set.
      * @return True if the 'DeliveryAddress' field has been set, false otherwise.
      */
    public boolean hasDeliveryAddress() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'DeliveryAddress' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public guide.atech.schema.avro.DeliveryAddress.Builder getDeliveryAddressBuilder() {
      if (DeliveryAddressBuilder == null) {
        if (hasDeliveryAddress()) {
          setDeliveryAddressBuilder(guide.atech.schema.avro.DeliveryAddress.newBuilder(DeliveryAddress));
        } else {
          setDeliveryAddressBuilder(guide.atech.schema.avro.DeliveryAddress.newBuilder());
        }
      }
      return DeliveryAddressBuilder;
    }

    /**
     * Sets the Builder instance for the 'DeliveryAddress' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public guide.atech.schema.avro.PosInvoice.Builder setDeliveryAddressBuilder(guide.atech.schema.avro.DeliveryAddress.Builder value) {
      clearDeliveryAddress();
      DeliveryAddressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'DeliveryAddress' field has an active Builder instance
     * @return True if the 'DeliveryAddress' field has an active Builder instance
     */
    public boolean hasDeliveryAddressBuilder() {
      return DeliveryAddressBuilder != null;
    }

    /**
      * Clears the value of the 'DeliveryAddress' field.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder clearDeliveryAddress() {
      DeliveryAddress = null;
      DeliveryAddressBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'InvoiceLineItems' field.
      * @return The value.
      */
    public java.util.List<guide.atech.schema.avro.LineItem> getInvoiceLineItems() {
      return InvoiceLineItems;
    }

    /**
      * Sets the value of the 'InvoiceLineItems' field.
      * @param value The value of 'InvoiceLineItems'.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder setInvoiceLineItems(java.util.List<guide.atech.schema.avro.LineItem> value) {
      validate(fields()[5], value);
      this.InvoiceLineItems = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'InvoiceLineItems' field has been set.
      * @return True if the 'InvoiceLineItems' field has been set, false otherwise.
      */
    public boolean hasInvoiceLineItems() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'InvoiceLineItems' field.
      * @return This builder.
      */
    public guide.atech.schema.avro.PosInvoice.Builder clearInvoiceLineItems() {
      InvoiceLineItems = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public PosInvoice build() {
      try {
        PosInvoice record = new PosInvoice();
        record.InvoiceNumber = fieldSetFlags()[0] ? this.InvoiceNumber : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.CreatedTime = fieldSetFlags()[1] ? this.CreatedTime : (java.lang.Long) defaultValue(fields()[1]);
        record.TotalAmount = fieldSetFlags()[2] ? this.TotalAmount : (java.lang.Double) defaultValue(fields()[2]);
        record.NumberOfItems = fieldSetFlags()[3] ? this.NumberOfItems : (java.lang.Integer) defaultValue(fields()[3]);
        if (DeliveryAddressBuilder != null) {
          record.DeliveryAddress = this.DeliveryAddressBuilder.build();
        } else {
          record.DeliveryAddress = fieldSetFlags()[4] ? this.DeliveryAddress : (guide.atech.schema.avro.DeliveryAddress) defaultValue(fields()[4]);
        }
        record.InvoiceLineItems = fieldSetFlags()[5] ? this.InvoiceLineItems : (java.util.List<guide.atech.schema.avro.LineItem>) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
